name: bambooapp
description: A Flutter app for bamboo classification.
publish_to: "none" # Prevent publishing to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  image: 4.0.17
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
